/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.example;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class standardConstants {

  public static final int MAX_RESULTS = 100;

}
