/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.example;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-13")
public class TweetSearchResult implements org.apache.thrift.TBase<TweetSearchResult, TweetSearchResult._Fields>, java.io.Serializable, Cloneable, Comparable<TweetSearchResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TweetSearchResult");

  private static final org.apache.thrift.protocol.TField TWEETS_FIELD_DESC = new org.apache.thrift.protocol.TField("tweets", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TweetSearchResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TweetSearchResultTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<Tweet> tweets; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TWEETS((short)1, "tweets");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TWEETS
          return TWEETS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TWEETS, new org.apache.thrift.meta_data.FieldMetaData("tweets", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.LIST        , "TweetList")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TweetSearchResult.class, metaDataMap);
  }

  public TweetSearchResult() {
  }

  public TweetSearchResult(
    java.util.List<Tweet> tweets)
  {
    this();
    this.tweets = tweets;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TweetSearchResult(TweetSearchResult other) {
    if (other.isSetTweets()) {
      java.util.List<Tweet> __this__tweets = new java.util.ArrayList<Tweet>(other.tweets.size());
      for (Tweet other_element : other.tweets) {
        __this__tweets.add(new Tweet(other_element));
      }
      this.tweets = __this__tweets;
    }
  }

  public TweetSearchResult deepCopy() {
    return new TweetSearchResult(this);
  }

  public void clear() {
    this.tweets = null;
  }

  public int getTweetsSize() {
    return (this.tweets == null) ? 0 : this.tweets.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Tweet> getTweetsIterator() {
    return (this.tweets == null) ? null : this.tweets.iterator();
  }

  public void addToTweets(Tweet elem) {
    if (this.tweets == null) {
      this.tweets = new java.util.ArrayList<Tweet>();
    }
    this.tweets.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Tweet> getTweets() {
    return this.tweets;
  }

  public TweetSearchResult setTweets(@org.apache.thrift.annotation.Nullable java.util.List<Tweet> tweets) {
    this.tweets = tweets;
    return this;
  }

  public void unsetTweets() {
    this.tweets = null;
  }

  /** Returns true if field tweets is set (has been assigned a value) and false otherwise */
  public boolean isSetTweets() {
    return this.tweets != null;
  }

  public void setTweetsIsSet(boolean value) {
    if (!value) {
      this.tweets = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TWEETS:
      if (value == null) {
        unsetTweets();
      } else {
        setTweets((java.util.List<Tweet>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TWEETS:
      return getTweets();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TWEETS:
      return isSetTweets();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TweetSearchResult)
      return this.equals((TweetSearchResult)that);
    return false;
  }

  public boolean equals(TweetSearchResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tweets = true && this.isSetTweets();
    boolean that_present_tweets = true && that.isSetTweets();
    if (this_present_tweets || that_present_tweets) {
      if (!(this_present_tweets && that_present_tweets))
        return false;
      if (!this.tweets.equals(that.tweets))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTweets()) ? 131071 : 524287);
    if (isSetTweets())
      hashCode = hashCode * 8191 + tweets.hashCode();

    return hashCode;
  }

  public int compareTo(TweetSearchResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTweets()).compareTo(other.isSetTweets());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTweets()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tweets, other.tweets);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TweetSearchResult(");
    boolean first = true;

    sb.append("tweets:");
    if (this.tweets == null) {
      sb.append("null");
    } else {
      sb.append(this.tweets);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TweetSearchResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TweetSearchResultStandardScheme getScheme() {
      return new TweetSearchResultStandardScheme();
    }
  }

  private static class TweetSearchResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TweetSearchResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TweetSearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TWEETS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.tweets = new java.util.ArrayList<Tweet>(_list0.size);
                @org.apache.thrift.annotation.Nullable Tweet _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new Tweet();
                  _elem1.read(iprot);
                  struct.tweets.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTweetsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TweetSearchResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tweets != null) {
        oprot.writeFieldBegin(TWEETS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tweets.size()));
          for (Tweet _iter3 : struct.tweets)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TweetSearchResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TweetSearchResultTupleScheme getScheme() {
      return new TweetSearchResultTupleScheme();
    }
  }

  private static class TweetSearchResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TweetSearchResult> {

    public void write(org.apache.thrift.protocol.TProtocol prot, TweetSearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTweets()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTweets()) {
        {
          oprot.writeI32(struct.tweets.size());
          for (Tweet _iter4 : struct.tweets)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    public void read(org.apache.thrift.protocol.TProtocol prot, TweetSearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tweets = new java.util.ArrayList<Tweet>(_list5.size);
          @org.apache.thrift.annotation.Nullable Tweet _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new Tweet();
            _elem6.read(iprot);
            struct.tweets.add(_elem6);
          }
        }
        struct.setTweetsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

